[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "joshhsoj1902"
name = "Agent_Modpack"
description = "A modpack used by the agents"
websiteUrl = "https://github.com/joshhsoj1902/lethal-company-agent-modpack"
containsNsfwContent = false

[build]
icon = "icon.png"
readme = "README.md"
outdir = "dist"

[[build.copy]]
source = "BepInEx"
target = "/BepInEx"

[publish]
communities = [ "lethal-company", ]

[package.dependencies]
###################
## Shared libraries
###################
BepInEx-BepInExPack = "5.4.2100"
AinaVT-LethalConfig = "1.4.3"
Rune580-LethalCompany_InputUtils = "0.7.7"
Evaisa-HookGenPatcher = "0.0.5"
Evaisa-LethalLib = "0.16.2"
Evaisa-FixPluginTypesSerialization = "1.1.1"
MaxWasUnavailable-LethalModDataLib = "1.2.2"
IAmBatby-LethalLevelLoader = "1.3.13"
Ozone-Runtime_Netcode_Patcher = "0.2.5"
Hardy-LCMaxSoundsFix = "1.2.0"
mrov-MrovLib = "0.2.16"
Bobbie-FixRPCLag = "1.0.1"
linkoid-DissonanceLagFix = "1.0.0"
xilophor-StaticNetcodeLib = "1.1.1"
Kittenji-NavMeshInCompany = "1.0.3"
NotAtomicBomb-TerminalApi = "1.5.5"

#############################
## Essential Multiplayer Mods
#############################
notnotnotswipez-MoreCompany = "1.11.0"
anormaltwig-LateCompany = "1.0.18"
ShaosilGaming-GeneralImprovements = "1.4.4"
KlutzyBubbles-BetterEmotes = "1.5.4"
FlipMods-TooManyEmotes = "2.2.14"

## Suits
Hexnet111-SuitSaver = "1.2.1"
x753-More_Suits = "1.4.5"
Verity-TooManySuits = "2.0.1"
GhostbustingTrio-CustomFunSuits = "1.8.3"
kidcudilovers-CudisRealisticSuits = "1.0.0"
404_Dom-Doms_Basic_Suit_Colors = "1.4.4"

###########
## QoL Mods
###########
dummy-LetTheDeadRest = "1.0.2"
FlipMods-ReservedItemSlotCore = "2.0.39"
FlipMods-ReservedFlashlightSlot = "2.0.8"
FlipMods-ReservedWalkieSlot = "2.0.6"
FlipMods-ReservedSprayPaintSlot = "1.1.2"
EliteMasterEric-Coroner = "2.2.0"
taffyko-BetterSprayPaint = "2.0.9"
Suskitech-AlwaysHearActiveWalkies = "1.4.5"
Monkeytype-HideChat = "1.0.0"
tinyhoot-ShipLoot = "1.1.0"
FutureSavior-Hold_Scan_Button = "1.1.2"
Spyci-CozyImprovements = "1.2.2"
mrov-TerminalFormatter = "0.2.25"
red_eye-LethalAutocomplete = "0.4.5"
ViViKo-SpectateDeathCause = "1.0.0"
MrHydralisk-MajorityVote = "1.1.0"

#############################
## Tweaking base game content
#############################
TwinDimensionalProductions-CoilHeadStare = "1.0.9"
sunnobunno-YippeeMod = "1.2.4"
qwbarch-Mirage = "1.15.5"
qwbarch-MirageCore = "1.0.3"
mattplays-HoarderBugUseItems = "1.0.3"
# Dogs are immune to shotguns in the base game.
AgentRev-ShootableMouthDogs = "1.0.1"
Sakura-LandminesForAll = "1.0.1"

## Sound changes
no00ob-LCSoundTool = "1.5.1"
Clementinise-CustomSounds = "2.3.2"
loaforc-loaforcsSoundAPI = "1.1.7"
ButteryStancakes-EnemySoundFixes = "1.6.2"
LethalResonance-LETHALRESONANCE = "4.7.5"
Sk737-JesterSymphony = "1.2.0"

#################################
## Adding new content to the game
#################################

## New scrap (and sometimes a couple store items)
Jordo-NeedyCats = "1.2.2"
slayer6409-Emergency_Dice_Updated = "1.7.4"
SimonTendo-LCGoldScrapMod = "2.0.6"
XuXiaolan-ImmersiveScrap = "1.4.1"
Sconeys-abandonedcompanyassets = "0.15.79"
ohotdog-LootableMusicTapes = "1.0.1"
bigmcnugget-VanillaContentExpansion = "0.1.8"
etherealemil-UsualScrap = "1.7.7"
Caigan-Tokucade_Scrap = "1.7.0"
# depends on deprecated package
# czech_lethal-AlltheScrapsMod = "1.1.7"
# I love pikmin, but these don't really match the correct theme
# Pikmanfan2002-PikminScrap = "2.0.0"
# depends on deprecated package
# ViViKo-AllTheScrap = "1.0.1"
FlipMods-TooManyEmotesScrap = "1.0.8"

# New Store Items
Dio93-DuckMod = "1.6.0"
Mellowdy-LightningRod = "1.0.5"
Zaggy1024-OpenBodyCams = "3.0.3"

# New creatures
x753-Peepers = "1.0.3"
zealsprince-Locker = "1.6.1"
Kittenji-Football = "1.1.11"
Sconeys-Gnomes = "2.1.19"
Kittenji-Herobrine = "1.3.6"
XuXiaolan-PjonkGoose = "1.5.0"
# Might not leave this in...
Garf-MissileTurrets = "1.3.5"
x753-Mimics = "2.6.4"

# New features
Entity378-SellBodiesFixed = "1.11.2"
mrgrm7-LethalCasino = "1.1.2"

#######################
# New dungeons & moons
#######################
theMenagerie-LiminalPools = "1.0.14"
MrUnrealTeam-SchoolDungeon = "1.3.1"
AudioKnight-StarlancerEnemyEscape = "2.5.7"
AudioKnight-StarlancerWarehouse = "1.6.7"
AudioKnight-StarlancerAIFix = "3.8.4"
AudioKnight-StarlancerMusic = "1.3.2"
AudioKnight-StarlancerMoons = "2.4.0"
AudioKnight-Starlancer = "2.0.0"

##############################
# Client side Graphics, UI & Perf
##############################
Sligili-HDLethalCompany = "1.5.6"
FlipMods-MoreBlood = "1.0.3"
sfDesat-ViewExtension = "1.3.0"
Confusified-InsanityDisplay = "1.2.2"
fumiko-CullFactory = "1.6.3"

#######
# Misc
#######
alexanderjoe-LC_Symphony = "1.3.0"
