name: Build

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g., for dependabot pull requests)
  push:
    branches: [main]
  # Trigger the workflow on any pull request
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: "A tag reference passed from Publish workflow"
        default: ${{ github.sha }}
        required: false
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.100"

      - name: build zip
        env:
          VERSION: ${{ inputs.ref }}
        run: |
          ./do build


      - name: debugging
        run: |
          dotnet tool install -g tcli
          tcli build
          ls -ltr
          ls -ltr dist

      - name: Upload Thunderstore artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./publish.zip
          retention-days: 7
      - name: Upload blah artifact
        uses: actions/upload-artifact@v4
        with:
          name: blah
          path: ./dist/joshhsoj1902-Agent_Modpack-0.0.1.zip
          retention-days: 7

