name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.100"

      - name: Install Thunderstore CLI
        run: |
          dotnet tool install -g tcli

      - name: Build
        run: |
          tcli build --package-version ${{ inputs.ref }}

      - name: Publish
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_KEY }}
        run: tcli publish --package-version "0.5.21" --package-name Agent_Modpack_TESTING

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore
          path: ./dist/*
          retention-days: 7

