name: Publish

on:
  release:
    types: [prereleased, released]
  workflow_call:
    inputs:
      tag:
        description: "A tag reference passed from Publish workflow"
        default: ${{ github.sha }}
        required: false
        type: string

jobs:
  upload-release-artifacts:
    name: Release artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.100"

      - name: Install Thunderstore CLI
        run: |
          dotnet tool install -g tcli

      - name: Publish
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.THUNDERSTORE_API_KEY }}
        run: tcli publish --package-version ${{ github.event.release.tag_name }}

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: gh release upload ${{ github.event.release.tag_name }} dist/*
