name: Release on Thunderstore

on:
  workflow_call:
    secrets:
      thunderstore-token:
        required: true

jobs:
  thunderstore:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Download Thunderstore artifact
        uses: actions/download-artifact@v4
        with:
          name: thunderstore-build

      - name: Setup .NET environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.100"

      - name: Install Evaisa's netcode-patcher
        run: |
          dotnet tool install -g tcli

      - name: Publish to Thunderstore
        env:
          TCLI_AUTH_TOKEN: ${{ secrets.thunderstore-token }}
        run: |
          # tcli publish --file thunderstore-build/publish.zip --token $TCLI_AUTH_TOKEN
          tcli publish --file thunderstore-build/publish.zip